---
title: "Integrated Reaction Norm"
output: pdf_document
date: "2025-03-25"
#last modified 3/31/25
---

# Set up 

```{r, setup}

rm(list = ls())

###
### Packages
###

library(tidyverse)
library(bayesplot)
library(cmdstanr)
```

#### Split the data
```{r}
## with combined dataframe 
allsites_flower_harvest <- read.csv("/Users/Becca/Desktop/Adler Lab/Bromecast-reaction_norms/combined_clean_climate.csv", header = TRUE) #%>%

bioclim <- read_csv("/Users/Becca/Desktop/Adler Lab/Bromecast-reaction_norms/combined_clean_climate.csv") 

### split training and test data 
allsites_flower_harvest <- allsites_flower_harvest %>%
  mutate(site_year = paste(site, year))

allsites_flower_harvest$site <- as.factor(allsites_flower_harvest$site)
allsites_flower_harvest$year <- as.factor(allsites_flower_harvest$year)
allsites_flower_harvest$site_year <- as.factor(allsites_flower_harvest$site_year)

bioclim$site <- as.factor(bioclim$site)
bioclim$year <- as.factor(bioclim$year)
bioclim <- bioclim %>%
  mutate(site_year = paste(site, year))
bioclim$site_year <- as.factor(bioclim$site_year)



data_sat <- allsites_flower_harvest%>% filter(Type == "Satellite")

set.seed(123)  # For reproducibility

selected_categories <- data_sat %>%
  distinct(site_year) %>%  
  slice_sample(n = 36) %>% 
  pull(site_year)          

training_data <- allsites_flower_harvest %>%
  filter(site_year %in% selected_categories | Type == "Common_Garden")

testing_data <- allsites_flower_harvest %>%
  filter(!(site_year %in% selected_categories) & Type == "Satellite")

### compare data to make sure we have decent coverage of climate 
library(ggplot2)

# Add a column to indicate the dataset source
training_data$Dataset <- "Training"
testing_data$Dataset <- "Testing"

# Combine the datasets
combined_data <- rbind(training_data, testing_data)

# Plot overlapping histograms
ggplot(combined_data, aes(x = tmean.Spr, fill = Dataset)) +
  geom_histogram(alpha = 0.5, bins = 30, position = "identity") +
  labs(title = "Temperature Distribution: Training vs Testing") +
  theme_minimal() +
  scale_fill_manual(values = c("Training" = "blue", "Testing" = "red"))

## for use in model 
bioclim <- bioclim %>%
  filter(site_year %in% selected_categories | Type == "Common_Garden")

```


# Real Data Preparation (Cheatgrass: Common Gardens)

```{r, Real Data Preparation (Cheatgrass: Common Gardens)} 

###
### Data (Common Gardens)
###

# Read in data that matches kinship matrix position and genotype ID

#dir="/Users/justinvanee/Library/Mobile Documents/com~apple~CloudDocs/Documents/bromecast/Cheatgrass"
#kinshipIDs <- read.csv(file=paste(dir, "93cg_genotypes.csv", sep="/"))

kinshipIDs <- read.csv("/Users/Becca/Desktop/Adler Lab/Bromecast-reaction_norms/data/common_gardens/93cg_genotypes.csv")

### This has all traits for all 4 common garden sites from 2022



  #Subset trait data for only genotypes that we have kinship data for
 # filter(genotype %in% kinshipIDs$genotype) # Right now this only drops 329 plants total and 4 genotypes


#allsites_flower_harvest <-
  #read.csv(file=paste(dir, "cg_cleandata_VanEe_PPCA.csv", sep="/")) %>%
# Subset trait data for only genotypes that we have kinship data for
 # filter(genotype %in% kinshipIDs$genotype) # Right now this only drops 329 plants total and 4 genotypes

### Genotypes Common Gardens  
genotypes_common_gardens <- 
  kinshipIDs %>%
  mutate(source = as.factor(source)) %>%
  filter(genotype %in% unique(allsites_flower_harvest$genotype)) %>%
  arrange(NewSiteCode)


# Read in data that matches kinship matrix position and genotype ID
# Read in kinship matrix for 307 genotypes 
#kinship <- read.table(paste(dir, "BRTE307_IBSmatrix.txt", sep="/"), sep=",")

kinship <- read.table("/Users/Becca/Desktop/Adler Lab/Bromecast-reaction_norms/data/BRTE307_IBSmatrix.txt", sep=",")

# Filter for common garden genotypes 
K_common_garden <- as.matrix(kinship[genotypes_common_gardens$kinshipID,genotypes_common_gardens$kinshipID])

# Put genotype numbers on rows and columns
colnames(K_common_garden) <- rownames(K_common_garden) <- as.factor(genotypes_common_gardens$NewSiteCode)

###
### Back to Common gardens data manipulations 
###
#allsites_flower_harvest <- allsites_flower_harvest %>% mutate(site_year = paste(site, year)) 


### Calculate Seed(m) and Biomass and set all attributes to NA for plants that didn't survive to Reproduce

df <- training_data %>%
  filter(Emerged == "Y", Reproduced == "Y") %>%
  mutate(
    site_numeric = as.numeric(as.factor(site)),
    site_year_numeric = as.numeric(as.factor(site_year)),
    year_numeric = as.numeric(as.factor(year)) - 1,
    genotype = if_else(is.na(genotype), 33, genotype)  # Assign random genotype for now 
  ) %>%
  dplyr::select(genotype, site_year, site, "Fecundity", "Biomass", "Reproduced") %>%
  left_join(kinshipIDs, by = "genotype") %>%
  filter(!is.na(NewSiteCode), !is.na(Fecundity))  %>% filter(Fecundity > 0) #some that have zero seeds otherwise included bc coded as reproduced 


### Covariate matrix 
Environments_classification <-
  training_data %>%  filter(Emerged == "Y", Reproduced == "Y") %>%  
  filter(!is.na(Fecundity)) %>% filter(Fecundity > 0) %>% 
  mutate(site_numeric=as.numeric(as.factor(site)),
         site_year_numeric=as.numeric(as.factor(site_year)),
    
         year_numeric=as.numeric(as.factor(year))-1) %>%
  dplyr::select(site, site_year) %>% 
  distinct() %>%
  arrange(site_year)  

### Bring in bioclimate variables 
# Bromecast repository
#bioclim <- read_csv("https://raw.githubusercontent.com/pbadler/bromecast-data/main/gardens/deriveddata/BioclimateOfOrigin_AllGenotypes.csv")


bioclim <- bioclim %>%  filter(Emerged == "Y", Reproduced == "Y") %>%  
  filter(!is.na(Fecundity)) %>% filter(Fecundity > 0) %>% dplyr::select(site,  year, site_year, Type, prcp.Spr, tmean.Spr, swe_mean.Spr, prcp.Sum, tmean.Sum, 
   prcp.Win, tmean.Win, swe_mean.Win, prcp.Fall, 
  tmean.Fall, swe_mean.Fall, MAT, 
  total_precip, seasonality) %>% distinct()
  ## if you don't do Fecundity >0 some are still retained with zero seeds
unique_sites <- unique(bioclim$site) 
idx_sites <- match(unique_sites, bioclim$site) 



## site year idx
site_year_idx <- unique(as.integer(factor(bioclim$site_year)))
## do we want this as an integer or categorical variable? 

# Run PCA
#pca_out <- prcomp(scale(bioclim[,5:ncol(bioclim)]))
climate_vars <- c(
  "prcp.Spr", "tmean.Spr", "swe_mean.Spr", "prcp.Sum", "tmean.Sum", 
   "prcp.Win", "tmean.Win", "swe_mean.Win", "prcp.Fall", 
  "tmean.Fall", "swe_mean.Fall", "MAT", 
  "total_precip", "seasonality"
)

clean_bioclim <- bioclim[, climate_vars] %>%
  filter(complete.cases(.))  # Removes rows with any NA values

pca_out <- prcomp(scale(clean_bioclim))

n_X <- nrow(bioclim)
q_X <- 2
Lambda <- as.matrix(pca_out$rotation[, 1:q_X])


n_X <- nrow(bioclim)
q_X <- 2
Lambda <- as.matrix(pca_out$rotation[,1:q_X])

### Create linkage matrix 
df$site_year <- as.factor(df$site_year)
df$site_year <- droplevels(df$site_year)
Z <- model.matrix(~ site_year - 1, data = df)

### Create linkage matrix (for four sites)
unique_sites <- unique(bioclim$site)  
site_match <- match(unique_sites, bioclim$site)  
idx_plant <- match(df$site, unique_sites)  


 print(range(idx_plant))   # Should be between 1 and length(idx_sites)
print(length(idx_sites))  # Should match the max value in idx_plant


### Extract genotype of each plant 
genotype_plant <- as.numeric(as.factor(df$NewSiteCode))

### Bioclimatic covariates 

#allcov <- Environments_classification %>%
 # mutate(intercept = 1,
         # density_n = as.numeric(density == "hi"), # These effects aren't estimated well in the data, huge variance 
        # gravel_n = as.numeric(albedo == "black")) %>%  # 
         # interaction = gravel_n * density) %>%  # 
 # left_join(bioclim[idx_sites, c(1, 5:ncol(bioclim))], by = c("site" = "site_code"))

allcov <- bioclim %>% select("site", "site_year", "year", all_of(climate_vars)) %>% distinct() 

#allcov <-  Environments_classification  %>%  mutate(intercept = 1,
     #   gravel_n = as.numeric(albedo == "black")) %>% 
#  left_join(bioclim[, c("site", climate_vars)], by = c("site"))


### Bioclimatic covariates 
#X <- scale(bioclim[,5:ncol(bioclim)]) 
bioclim_clean <- na.omit(bioclim[, climate_vars])
X <- scale(bioclim_clean[, climate_vars])


### Treatment covariates  
#V <- Z %*% as.matrix(allcov[,5:8]) #5-8 was intercept, density-n, gravel-n and interaction
  #n = nrow(V), #number of observations
#  p_V = ncol(V), #Number of treatments + 1 for intercept
V <- Z

### Extract fecundity 
y <-
  df %>%
  pluck("Fecundity") 
  #pluck("Seed(n)")

```

# Fit Stan Model 

```{r, fit stan model}

## note manually change the number of sites in stan code to match length(stan_data$idx_sites) 
 
# Data list for Stan
stan_data <- list(
  # Dimension of objects
  n_g = max(genotype_plant), #number of genotypes
  n = nrow(V), #number of observations
  p_V = ncol(V), #Number of treatments + 1 for intercept
  n_X = nrow(X), #number of obs of climate variables 
  q_X = ncol(Lambda), #Number of latent factors
  p_X = nrow(Lambda), #number of climate variables 
  # Response (fecundity)
  y = y,
  # Matrices 
  Lambda = Lambda,
  V = V,
  X = X,
  # Kinship
  K = K_common_garden,
  # For linking plants with genotypes and treatments 
  idx_sites = idx_sites,
  idx_plant = idx_plant,
  genotype_plant = genotype_plant #,
  # site_year_idx = site_year_idx #,  
  #n_site_year = length(unique(site_year_idx))  
)

# Warmup and iterations 
iter_warmup = 100
iter_sampling = 1000

# Fit using cmdrstan 
mod <- cmdstan_model("ztp_glm.stan")
#mod <- cmdstan_model("ztp_glm.stan_with_intercept") #for site_year random intercept 

# Compile and fit the model
fit <- mod$sample(
  data = stan_data,
  seed = 123,
  chains = 4,
  parallel_chains = 4,
  iter_warmup = iter_warmup,
  iter_sampling = iter_sampling
)

# Summary of results
fit$summary()

# Extract posterior samples
posterior <- fit$draws(variables = c("beta", "gamma", "sigma", "W", "zeta"))

#
# Traceplots for diagnostics
#

# beta
color_scheme_set("mix-blue-pink")
p <- mcmc_trace(posterior,  pars = c("beta[1,1]","beta[2,1]"), n_warmup = iter_warmup)
p + facet_text(size = 15)

# gamma
color_scheme_set("mix-blue-pink")
p <- mcmc_trace(posterior[51:200,,],  pars = paste0("gamma[", 1:ncol(V), "]"), n_warmup = iter_warmup)
p + facet_text(size = 15)

# sigma
color_scheme_set("mix-blue-pink")
p <- mcmc_trace(posterior,  pars = paste0("sigma[", 1:ncol(X), "]"), n_warmup = iter_warmup)
p + facet_text(size = 15)

# zeta
color_scheme_set("mix-blue-pink")
p <- mcmc_trace(posterior[51:200,,],  pars = paste0("zeta[", 1:q_X, "]"), n_warmup = iter_warmup)
p + facet_text(size = 15)

# W
color_scheme_set("mix-blue-pink")
p <- mcmc_trace(posterior,  pars = c("W[1,1]","W[1,2]", "W[101,1]", "W[101,2]"), n_warmup = iter_warmup)
p + facet_text(size = 15)
```

# Simulation Study

```{r, simulation study}


# 
p_X=20
q_X=2
n_X=100
n=1000
X=matrix(rnorm(p_X * n_X), n_X, p_X)
pc_out=prcomp(X)
Lambda=pc_out$rotation[,1:q_X]
W=pc_out$x[,1:q_X]

```

